# render.yaml

services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python -m bot
    envVars:
      - key: SESSION
        value: yato
      - key: TOKEN
        value: 642712
      - key: API_ID
        value: ""  # Add your API ID here
      - key: API_HASH
        value: ""  # Add your API Hash here
      - key: PORT
        value: 5010
      - key: OWNER_ID
        value: 6497757690
      - key: DB_URI
        value: mongodb  # Replace with your MongoDB URI
      - key: DB_NAME
        value: yato
